apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-service-deployment
spec:
  selector:
    matchLabels:
      app: file-service
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: file-service
    spec:
      containers:
      - name: file-service # the one from which pod get created
        image: truptikat88/file-service:v1.0.0 #the one which we give in docker build
        ports:
        - containerPort: 8081